name = "MathTools"
uuid = "4f755ac4-ec4f-11e8-0bd3-5729e5d9ca6a"
authors = ["Sebastian Schaffer <schaffer.sebastian@gmx.at>"]
version = "0.1.0"

[deps]
IJulia = "7073ff75-c697-5162-941a-fcdaad2a7d2a"
